language: java

jdk:
  - openjdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "I3+AlmRguLTShB7E411tgW0/u2oMWTdNO9Re27KjRanHERLDWRDsjOHHaKoK2MZ5Mv6k8KogfRzgongChJXNyVCoKoFj4kowMzzQypEL/bXNj7YNXmDbFUpDSaxlBPnbCAL03ZoHbH1r60ZZQY+w/p8HHLFfwQSRHiuxW2iZCjY="
    - secure: "EBmDKP8/wGPfP6NTb8P3WOfLeFwTpJwQsajTkKTpeVtEvRr6cpKe1W85nQgdiWed5j7Tw6br7E937uYZP9s54TFakq8uMw9OQrHzboN+fYc41sDQoxobZLypHFt3kxoyWkOKu18P5timvMXUdXge2/A0CTj4ZKG6z1N6vhY8MM0="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
